/* 
 * Copyright (c) 2022 Huawei Technologies Co.,Ltd.
 *
 * openGauss is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *
 *           http://license.coscl.org.cn/MulanPSL2
 *        
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */

package org.opengauss.mppdbide.utils.observer;

/**
 * 
 * Title: interface
 * 
 * Description: The Interface IDSGridUIListenable.
 *
 * @since 3.0.0
 */
public interface IDSGridUIListenable extends IDSListenable {
    int LISTEN_TYPE_PRE_GRID_DATA_LOAD = 1;
    int LISTEN_TYPE_POST_GRID_DATA_LOAD = 2;
    int LISTEN_TYPE_ON_ERROR = 3;
    int LISTEN_TYPE_ON_REEXECUTE_QUERY = 4;
    int LISTEN_TYPE_GRID_DATA_CHANGED = 5;
    int LISTEN_TYPE_EXPORT_CURR_PAGE_DATA = 6;
    int LISTEN_TYPE_EXPORT_ALL_DATA = 7;
    int LISTEN_TYPE_GRID_DATA_EDITED = 8;
    int LISTEN_EDITTABLE_COMMIT_DATA = 9;
    int LISTEN_EDITTABLE_COMMIT_STATUS = 10;
    int LISTEN_DATABASE_CONNECT_DISCONNECT_STATUS = 11;
    int LISTEN_EDITTABLE_USER_FORGET_OPTION = 12;
    int LISTEN_EDITTABLE_REMEMBERED_USER_OPTION = 13;
    int LISTEN_TYPE_ON_GRID_CREATION = 14;
    int LISTEN_EDITTABLE_COMMIT_DATA_COMPLETE = 15;
    int LISTEN_TYPE_SEARCH_DONE = 16;
    int LISTEN_TYPE_SEARCH_CLEARED = 17;
    int LISTEN_BATCHDROP_ATOMIC_OPTION = 18;
    int LISTEN_BATCHDROP_CASCADE_OPTION = 19;
    int LISTEN_BATCHDROP_START_OPTION = 20;
    int LISTEN_BATCHDROP_STOP_OPTION = 21;
    int LISTEN_BATCHDROP_DROP_SUCCESS = 22;
    int LISTEN_BATCHDROP_DROP_FAILED = 23;
    int LISTEN_BATCHDROP_OP_COMPLETE = 24;
    int LISTEN_BATCHDROP_GRID_INPUT_CHANGED = 25;
    int LISTEN_BATCHDROP_OP_ROLLBACK = 26;
    int LISTEN_BATCHDROP_JOB_CANCEL = 27;
    int LISTEN_BATCHDROP_DROP_REVERTED = 28;
    int LISTEN_BATCHDROP_DROP_FAIL_REVERTED = 29;
    int LISTEN_BATCHDROP_CONN_FAILED = 30;
    int LISTEN_EDITTABLE_ROLLBACK_DATA = 31;
    int LISTEN_TYPE_ON_REFRESH_QUERY = 32;
    int LISTEN_TYPE_PROPERITES_COMMIT_DATA = 33;
    int LISTEN_DATA_CHANGE_ENCODING = 34;
    int LISTEN_EDITTABLE_ROLLBACK_DATA_COMPLETE = 35;
    int LISTEN_BATCHEXPORT_DDL_SUCCESS = 36;
    int LISTEN_EXEC_PLAN_WINDOW_REFRESH = 39;
    int LISTEN_EXEC_PLAN_WINDOW_TREE_VIEW = 40;
    int LISTEN_EXEC_PLAN_WINDOW_TEXT_VIEW = 41;
    int LISTEN_EXEC_PLAN_WINDOW_SAVE_PLAN = 42;
    int LISTEN_TYPE_ROW_UPDATED = 43;
    int LISTEN_TYPE_ROW_DELETED = 44;
    int LISTEN_TYPE_CREATE_TABLESPACE_COMMITED_SUCCESS = 45;
    int LISTEN_TYPE_GRID_ROW_SELECTED = 46;
    int LISTEN_ROW_SELECTED = 47;
    int LIRTEN_ROLLBACK_PROPERTIES = 48;
    int LISTEN_EDITZPROPERTIES_POST_COMMIT = 49;
    int LISTEN_EDITZPROPERTIES_COMMIT_STATUS = 50;
    int LISTEN_TYPE_CREATE_TABLE_COMMITED_SUCCESS = 51;
    int LISTEN_CASESENSITIVITY_SELECTION = 52;
    int LISTEN_COPY_TO_EXCEL_XLSX_RESULT_WINDOW_MENUITEM = 53;
    int LISTEN_COPY_TO_EXCEL_XLS_RESULT_WINDOW_MENUITEM = 54;
    int LISTEN_TYPE_ON_RESULT_WINDOW_MENUITEM_SEARCH = 55;
    int LISTEN_TYPE_ON_RESULT_MENUITEM_GERERATE_SELECT_LINE_INSERT = 56;
    int LISTEN_TYPE_ON_RESULT_MENUITEM_GERERATE_CURRENT_PAGE_INSERT = 57;
    int LISTEN_TYPE_ON_RESULT_MENUITEM_GERERATE_ALL_INSERT = 58;
    int LISTEN_CREATE_TABLE_DDL_GENERATION = 59;
    int LISTEN_TYPE_ON_CANCEL_PASSWORD = 60;

}
