/* 
 * Copyright (c) 2022 Huawei Technologies Co.,Ltd.
 *
 * openGauss is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *
 *           http://license.coscl.org.cn/MulanPSL2
 *        
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */

package com.huawei.mppdbide.bl.serverdatacache;

/**
 * Title: enum Description: The Enum OBJECTTYPE.
 */

public enum OBJECTTYPE {
    PLSQLFUNCTION, PROCEDURE, TABLESPACE, TABLEMETADATA, SQLFUNCTION, CFUNCTION,
    // DS_ITR0_STRY_013 starts
    TYPEMETADATA, KEYWORDS,
    // DS_ITR0_STRY_013 ends
    NODE, NODEGROUP, ACCESSMETHOD, DATABASE, SQLTERMINAL, NODE_GROUP, FUNCTION_GROUP, PROCEDURE_GROUP, TABLE_GROUP,
    NODEGROUP_GROUP, DATABASE_GROUP, TABLESPACE_GROUP, DATATYPE_GROUP, NAMESPACE_GROUP, USER_NAMESPACE_GROUP,
    SYSTEM_NAMESPACE_GROUP, COLUMN_GROUP, CONSTRAINT_GROUP, INDEX_GROUP, ACCESSMETHOD_GROUP, OBJECTTYPE_BUTT, NAMESPACE,
    USER_NAMESPACE, SYSTEM_NAMESPACE, INDEX_METADATA, COLUMN_METADATA, CONSTRAINT, VIEW_META_DATA, VIEW_GROUP,
    VIEW_COLUMN_METADATA, VIEW_COLUMN_GROUP, FOREIGN_TABLE_GROUP, SEQUENCE_GROUP, SYNONYM_GROUP, USER_ROLE_GROUP,
    USER_ROLE, PARTITION_TABLE, FOREIGN_PARTITION_TABLE, PARTITION_GROUP, PARTITION_METADATA, FOREIGN_TABLE,
    FOREIGN_TABLE_GDS, FOREIGN_TABLE_HDFS, SEQUENCE_METADATA_GROUP, SYNONYM_METADATA_GROUP, ALIAS,
    TRIGGER,
    TRIGGER_GROUP, TRIGGER_METADATA,
    SHOW_MORE_OBJECTS
}
